/*
 * This file is generated by jOOQ.
*/
package com.bisaga.myapp.database.model;


import com.bisaga.myapp.database.model.tables.Currency;
import com.bisaga.myapp.database.model.tables.SchemaVersion;
import com.bisaga.myapp.database.model.tables.records.CurrencyRecord;
import com.bisaga.myapp.database.model.tables.records.SchemaVersionRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CurrencyRecord, Integer> IDENTITY_CURRENCY = Identities0.IDENTITY_CURRENCY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CurrencyRecord> CURRENCY_PKEY = UniqueKeys0.CURRENCY_PKEY;
    public static final UniqueKey<SchemaVersionRecord> SCHEMA_VERSION_PK = UniqueKeys0.SCHEMA_VERSION_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<CurrencyRecord, Integer> IDENTITY_CURRENCY = createIdentity(Currency.CURRENCY, Currency.CURRENCY.ROW_ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CurrencyRecord> CURRENCY_PKEY = createUniqueKey(Currency.CURRENCY, "currency_pkey", Currency.CURRENCY.ROW_ID);
        public static final UniqueKey<SchemaVersionRecord> SCHEMA_VERSION_PK = createUniqueKey(SchemaVersion.SCHEMA_VERSION, "schema_version_pk", SchemaVersion.SCHEMA_VERSION.INSTALLED_RANK);
    }
}
